<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Customer\Block\Account\Link $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<li class="link my-account-link">
    <a <?= /* @noEscape */ $block->getLinkAttributes() ?>><?= $escaper->escapeHtml($block->getLabel()) ?></a>
</li>
<li class="link my-orders-link">
    <a href="<?= $escaper->escapeUrl($block->getUrl('sales/order/history')) ?>">
                    <span><?= $escaper->escapeHtml(__('My Orders')) ?></span>
    </a>
</li>