<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */

use Magento\Checkout\Block\Onepage\Link;
use Magento\Framework\Escaper;
$checkoutBlcok = \Magento\Framework\App\ObjectManager::getInstance()->get(\Magento\Checkout\Block\Onepage\Link::class);
/**
 * 
 * @var Escaper $escaper
 */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) :?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       min="0"
                       value="<?= $block->getProductDefaultQty() * 1 ?>"
                       title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
            </div>
        </div>
        <?php endif; ?>
       <div class="cart-actions-container">
        <div class="actions actions--cart">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    id="product-addtocart-button" disabled>
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
        </div>
            <?php if ($checkoutBlcok->isPossibleOnepageCheckout()): ?>
            <div class="actions actions--checkout" style="margin-top: 20px;">
                    <!-- 立即购买按钮 -->
                    <button type="submit"
                            id="product-buynow-button"
                            title="<?= $escaper->escapeHtmlAttr(__('Proceed to Checkout')) ?>"
                            class="action primary buynow checkout<?= ($checkoutBlcok->isDisabled()) ? ' disabled' : '' ?>"
                            <?php if ($checkoutBlcok->isDisabled()): ?>
                                disabled="disabled"
                            <?php endif; ?>
                            onclick="var f=this.form;f.setAttribute('data-buynow','1');f.setAttribute('data-checkout-url','<?= $escaper->escapeJs($checkoutBlcok->getCheckoutUrl()) ?>');">
                        <span><?= $escaper->escapeHtml(__('Proceed to Checkout')) ?></span>
                    </button>
                </div>
    
    <?php endif?>
        </div>
         <?= $block->getChildHtml('', true) ?>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
