<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Checkout\Block\Onepage\Link;
use Magento\Framework\Escaper;

/**
 * @var Link $block
 * @var Escaper $escaper
 */
?>
<?php if ($block->isPossibleOnepageCheckout()): ?>
    <div class="actions actions--checkout">
            <!-- 立即购买按钮 -->
              <button type="button"
                    id="product-buynow-button"
                    data-role="proceed-to-checkout"
                    title="<?= $escaper->escapeHtmlAttr(__('Proceed to Checkout')) ?>"
                    data-mage-init='{
                        "Magento_Checkout/js/proceed-to-checkout":{
                            "checkoutUrl":"<?= $escaper->escapeJs($block->getCheckoutUrl()) ?>"
                        }
                    }'
                    class="action primary buynow checkout<?= ($block->isDisabled()) ? ' disabled' : '' ?>"
                    <?php if ($block->isDisabled()): ?>
                        disabled="disabled"
                    <?php endif; ?>>
                <span><?= $escaper->escapeHtml(__('Proceed to Checkout')) ?></span>
            </button>
        </div>
   
<?php endif?>
