<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View
 */
?>
<?php $_helper = $this->helper(Magento\Catalog\Helper\Output::class); ?>
<?php $_product = $block->getProduct(); ?>
    

    <div class="product-add-form">

        <form data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
            action="<?= $block->escapeUrl($block->getSubmitUrl($_product)) ?>" method="post"
            id="product_addtocart_form"<?php if ($_product->getOptions()) :?> enctype="multipart/form-data"<?php endif; ?> >
            <input type="hidden" name="product" value="<?= (int)$_product->getId() ?>" />
            <input type="hidden" name="selected_configurable_option" value="" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
            <input type="hidden" name="item"  value="<?= (int)$block->getRequest()->getParam('id') ?>" />
            <?= $block->getBlockHtml('formkey') ?>
          
            <div class="form-left-panel">
                <?= $block->getChildHtml('product.info.main.wrapper') ?>
                 <?= $block->getChildHtml('form_top') ?>
               
                    <?php if ($_product->isSaleable() && $block->getOptionsContainer() == 'container1') :?>
                        <?= $block->getChildChildHtml('options_container') ?>
                 
                   <?php endif; ?>
            <?php if ($_product->isSaleable() && $block->hasOptions() && $block->getOptionsContainer() == 'container2') :?>
                    <?= $block->getChildChildHtml('options_container') ?>
                <?php endif;?>
            </div>
        
            
                <div class="form-right-panel">
               <div class="cart-summary-panel">
                <?= $block->getChildHtml('product.form.chage.template') ?> 
                <?= $block->getChildHtml('product.info.main') ?>  
            </div>
                <?= $block->getChildHtml('product_options_wrapper_bottom')?>
                    <?= $block->getChildHtml('form_bottom') ?>
            
            </div>
        
        </form>
    </div>
<script type="text/x-magento-init">
    {
        "[data-role=priceBox][data-price-box=product-id-<?= $block->escapeHtml($_product->getId()) ?>]": {
            "priceBox": {
                "priceConfig":  <?= /* @noEscape */ $block->getJsonConfig() ?>
            }
        }
    }
</script>
