
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *  @var \Magento\Framework\Escaper $escaper
 */

/** @var Magento\Customer\Block\Account\Customer $block */
?>
<?php if ($block->customerLoggedIn()) : ?>
    <div class="folix-moblie-customer-welcome">
       
        <div class="customer-menu-moblie">
            <div class="user-menu">
                <a href="<?= $block->escapeUrl($block->getUrl('customer/account')) ?>">
                    <span><?= $block->escapeHtml(__('My Account')) ?></span>
                </a>
                <a href="<?= $block->escapeUrl($block->getUrl('sales/order/history')) ?>">
                    <span><?= $block->escapeHtml(__('My Orders')) ?></span>
                </a>
                <a href="<?= $block->escapeUrl($block->getUrl('wishlist')) ?>">
                    <span><?= $block->escapeHtml(__('My Wishlist')) ?></span>
                </a>
                <div class="divider"></div>
                <a href="<?= $block->escapeUrl($block->getUrl('customer/account/logout')) ?>" class="logout">
                    <span><?= $block->escapeHtml(__('Sign Out')) ?></span>
                </a>
            </div>
        </div>
</div>
<?php else: ?>
  <div class="folix-moblie-not-login">
    <ul>
      <li class="link authorization-link folix-auth-link" data-label="<?= $escaper->escapeHtml(__('or')) ?>">
         <span><?php  $escaper->escapeHtml('sign In');?></span><span> <?php  $escaper->escapeHtml('Create Account')?></span>
      </li>
      
    </ul>   
  </div>
<?php endif; ?>
