<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Framework\View\Element\Html\Links */
?>
<div class="block account-nav folix-account-nav">
    <div class="title folix-account-nav-title">
        <strong><?= $block->escapeHtml(__('My Account')) ?></strong>
    </div>
    <div class="content folix-account-nav-content">
        <nav class="account-nav">
            <ul class="nav items folix-account-nav-list">
                <?= $block->getChildHtml() ?>
            </ul>
        </nav>
    </div>
</div>
